### ISSUE TITLE
DIF/modules.py and configargparse.py

### ISSUE THREAD

**Issue by ccmCCMfk** [wurina-github/FGTrans#4]
Sorry to botter you,Is the above two files missed?

**Comment by wurina-github** [comment]
Sorry, the DIF is indeed missing the model.py. The file has been updated.

**Comment by ccmCCMfk** [comment]
thanks a lot.






                       
Original Email
                       
                     

Sender:"wurina-github"< ***@***.*** &gt;;

Sent Time:2023/11/21 15:24

To:"wurina-github/FGTrans"< ***@***.*** &gt;;

Cc recipient:"ccmCCMfk"< ***@***.*** &gt;;"Manual"< ***@***.*** &gt;;

Subject:Re: [wurina-github/FGTrans] DIF/modules.py and configargparse.py(Issue #4)




 
Sorry, the DIF is indeed missing the model.py. The file has been updated.
